package com.stmybatisenum.model;

import java.io.Serializable;

public class Person implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.ID
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.NAME
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.AGE
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERSON.GENDER
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.ID
     *
     * @return the value of PERSON.ID
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Person withId(Long id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.ID
     *
     * @param id the value for PERSON.ID
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.NAME
     *
     * @return the value of PERSON.NAME
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Person withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.NAME
     *
     * @param name the value for PERSON.NAME
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.AGE
     *
     * @return the value of PERSON.AGE
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Person withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.AGE
     *
     * @param age the value for PERSON.AGE
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERSON.GENDER
     *
     * @return the value of PERSON.GENDER
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public Person withGender(String gender) {
        this.setGender(gender);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERSON.GENDER
     *
     * @param gender the value for PERSON.GENDER
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERSON
     *
     * @mbg.generated Tue Jun 09 15:49:32 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append(", gender=").append(gender);
        sb.append("]");
        return sb.toString();
    }
}