package com.stshardingspherepostgresql.mapper;

import com.stshardingspherepostgresql.model.Person;
import com.stshardingspherepostgresql.model.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    @Insert({
        "insert into t_person1 (id, name, ",
        "age)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=INTEGER})"
    })
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    List<Person> selectByExampleWithRowbounds(PersonExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);
}