server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
    schema:
      - classpath:sql/schema.sql
    url: jdbc:h2:mem:chess
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    initialization-mode: always

#  jpa:
#    database: h2
#    hibernate:
#      ddl-auto: update

  #H2控制台:http://localhost:8090/h2-console
  h2:
    console:
      path: /h2-console
      enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      capital-mode: true