server:
  port: 8090

spring:
  output:
    ansi:
      enabled: always
  datasource:
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 5
#      idle-timeout: 600000
#      connection-timeout: 30000
#      max-lifetime: 1800000
#    schema:
#      - classpath:sql/schema.sql
    url: jdbc:postgresql://192.168.2.103:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456

#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      capital-mode: true
