package com.stshardingspherepostgresql.model;

import java.io.Serializable;

public class Person implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person1.id
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person1.name
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_person1.age
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person1.id
     *
     * @return the value of t_person1.id
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public Person withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person1.id
     *
     * @param id the value for t_person1.id
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person1.name
     *
     * @return the value of t_person1.name
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public Person withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person1.name
     *
     * @param name the value for t_person1.name
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_person1.age
     *
     * @return the value of t_person1.age
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public Person withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_person1.age
     *
     * @param age the value for t_person1.age
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_person1
     *
     * @mbg.generated Wed Jun 17 15:36:31 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}